version: "3.8"
services:
  analyzarr:
    image: dhclark18/analyzarr:latest
    ports:
      - "3000:80"
    environment:
      SONARR_URL: http://[sonarr_ip]:8989
      SONARR_API_KEY: [sonarr api key]
      CHECK_COOLDOWN: 5                    # in seconds
      TVDB_ID: [id]                        # optional TVDB ID for show you want to analyze
      SEASON_FILTER: [season]              # optional seaons in a show you want to analyze, or for multiple: SEASON_FILTER: 2,5,7  
      DATABASE_URL: [postgress db url]
      LOG_LEVEL: INFO                      # DEBUG also available
    volumes:
      - /path/to/tv/folder:/watched:ro
      - /path/to/logs:/logs                 #optional
    depends_on:
      postgres:
        condition: service_started   
        restart: true
                   
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: [user]       
      POSTGRES_PASSWORD: [password]
      POSTGRES_DB: [DB name]
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata:
