version: "3.8"
services:
  sonarr-scanner:
    build: .
    environment:
      SONARR_URL: http://192.168.1.71:8989
      SONARR_API_KEY: your-api-key
      CHECK_COOLDOWN: 60
    volumes:
      - /path/to/your/tv:/watched:ro
      - /path/to/logs:/logs
