version: "3.8"
services:
  sonarr-scanner:
    image: dhclark18/tv-episode-checker:latest
    environment:
      SONARR_URL: http://192.168.1.71:8989
      SONARR_API_KEY: your-api-key
      CHECK_COOLDOWN: 60
      DRY_RUN: true
      #LIMIT_SERIES_TVDBID: [tvdb_id]
    volumes:
      - /path/to/your/tv:/watched:ro
      - /path/to/logs:/logs
